### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by nyngwang** [letieu/hacker.nvim#2]
Got a blank buffer after `:Hack` & `:HackFollow`. My `setyup` is included in the demo.

https://user-images.githubusercontent.com/24765272/230275073-03e47b86-a53d-489d-8c23-65d056d3ba46.mov

**Comment by letieu** [comment]
You need enter input mode and type something, it not auto type, it write code when you type some key like hackertyper

**Comment by nyngwang** [comment]
Lol, I thought I was supposed to type something directly in Normal mode. Thanks for the hint let me try it again...

**Comment by nyngwang** [comment]
@letieu Now I got some error probably due to the fact that I didn't escape some characters. Could you provide the transformation out of the box? To reproduce, simply put `string.dump(require('to.your.file'))` to the option `content=`

<img src="https://user-images.githubusercontent.com/24765272/230303065-1497b502-6ca6-4469-8472-5afe03d34a12.png" width="500">

seems to cause by `^[@`.

**Comment by letieu** [comment]
> @letieu Now I got some error probably due to the fact that I didn't escape some characters. Could you provide the transformation out of the box? To reproduce, simply put `string.dump(require('to.your.file'))` to the option `content=`
> 
> 
> 
> <img src="https://user-images.githubusercontent.com/24765272/230303065-1497b502-6ca6-4469-8472-5afe03d34a12.png" width="500">
> 
> 
> 
> seems to cause by `^[@`.

Just open a file have some code,  try HackFollow

It just a funny project :)) 


Don't need call setup for simple

**Comment by nyngwang** [comment]
> It just a funny project :))
