### ISSUE TITLE
hacker.nvim writes unwanted characters

### ISSUE THREAD

**Issue by NStefan002** [letieu/hacker.nvim#4]
Hi. First of all, I absolutely love hacker.nvim. There is just one inconvenience that I have when using it. When I type random letters and press `j` it gets inserted in the buffer text. I guess it's because I have `jk` mapped to exit insert mode, so there is a slight delay when hitting `j`. Here is what I mean:

https://github.com/letieu/hacker.nvim/assets/100767853/f8683e7f-be4b-416f-aa17-844279de33ed

**Comment by letieu** [comment]
@NStefan002 actually, I'm not sure how to fix this. I'll need to think about it later.
